### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by WillTooEpic** [ChrisEric1/chriseric1.github.io#2] opened 2022-09-25 07:56 UTC
When I open the discord bot client it is always stuck on a grey screen, I have tried reloading many times but it's stuck on a grey screen

**Comment by CE1CECL** [comment] 2022-09-25 15:37
What browser are you using? This may be a duplicate of issue #1 but if you are using Firefox, first go to the site, then once loaded in completely install the extension. Have you even installed the extension or logged in (assuming you installed but on logged in) And what shows in console?

**Comment by CE1CECL** [comment] 2022-10-28 20:18
Closing due to inactivity..

**Closed as completed by CE1CECL** 2022-10-28 20:18 UTC
